//! Generates `src/el_table.rs`: the 128-bit truncated powers of five used
//! by the Eisel-Lemire float algorithm (Lemire, "Number Parsing at a
//! Gigabyte per Second"), the same table as fast_float /
//! fast_double_parser.
//!
//! ```text
//! cargo run --example gen_el_table > src/el_table.rs
//! ```
//!
//! Self-contained: the arbitrary-precision arithmetic below (a few dozen
//! lines over little-endian u64 limbs) exists so regenerating the table
//! needs nothing but this crate's toolchain.

/// Arbitrary-precision unsigned integer, little-endian u64 limbs, no
/// leading zero limb.
#[derive(Clone)]
struct BigU {
    limbs: Vec<u64>,
}

impl BigU {
    fn one() -> BigU {
        BigU { limbs: vec![1] }
    }

    fn mul_small(&mut self, m: u64) {
        let mut carry: u128 = 0;
        for limb in &mut self.limbs {
            let prod = u128::from(*limb) * u128::from(m) + carry;
            *limb = prod as u64;
            carry = prod >> 64;
        }
        if carry != 0 {
            self.limbs.push(carry as u64);
        }
    }

    fn bit_length(&self) -> usize {
        let top = *self.limbs.last().expect("no leading zero limbs");
        (self.limbs.len() - 1) * 64 + (64 - top.leading_zeros() as usize)
    }

    /// Bit `i` (little-endian numbering).
    fn bit(&self, i: usize) -> bool {
        self.limbs
            .get(i / 64)
            .is_some_and(|limb| limb >> (i % 64) & 1 == 1)
    }

    /// The most significant 128 bits (`self >> (bit_length - 128)`), as
    /// (hi, lo). Requires `bit_length() >= 128`.
    fn top128(&self) -> (u64, u64) {
        let shift = self.bit_length() - 128;
        let mut hi = 0u64;
        let mut lo = 0u64;
        for i in 0..64 {
            lo |= u64::from(self.bit(shift + i)) << i;
            hi |= u64::from(self.bit(shift + 64 + i)) << i;
        }
        (hi, lo)
    }

    fn cmp_bits(&self, other: &BigU) -> std::cmp::Ordering {
        let max = self.limbs.len().max(other.limbs.len());
        for i in (0..max).rev() {
            let a = self.limbs.get(i).copied().unwrap_or(0);
            let b = other.limbs.get(i).copied().unwrap_or(0);
            if a != b {
                return a.cmp(&b);
            }
        }
        std::cmp::Ordering::Equal
    }

    fn sub_assign(&mut self, other: &BigU) {
        let mut borrow = 0u64;
        for i in 0..self.limbs.len() {
            let b = other.limbs.get(i).copied().unwrap_or(0);
            let (r1, o1) = self.limbs[i].overflowing_sub(b);
            let (r2, o2) = r1.overflowing_sub(borrow);
            self.limbs[i] = r2;
            borrow = u64::from(o1) + u64::from(o2);
        }
        debug_assert_eq!(borrow, 0, "subtraction underflow");
    }

    /// Double in place and add `bit`: one step of building a remainder
    /// during binary long division.
    fn shl1_add(&mut self, bit: bool) {
        let mut carry = u64::from(bit);
        for limb in &mut self.limbs {
            let new_carry = *limb >> 63;
            *limb = (*limb << 1) | carry;
            carry = new_carry;
        }
        if carry != 0 {
            self.limbs.push(carry);
        }
    }
}

/// `5^n`.
fn pow5(n: u32) -> BigU {
    let mut v = BigU::one();
    for _ in 0..n {
        v.mul_small(5);
    }
    v
}

/// `floor(2^exp / divisor)`, for quotients known to fit 128 bits, by binary
/// long division; the dividend's bits are a single 1 followed by zeros.
fn div_pow2(exp: usize, divisor: &BigU) -> (u64, u64) {
    let mut remainder = BigU { limbs: vec![0] };
    let mut hi = 0u64;
    let mut lo = 0u64;
    for i in (0..=exp).rev() {
        remainder.shl1_add(i == exp); // dividend bit: 1 only at the MSB
        let q_bit = remainder.cmp_bits(divisor) != std::cmp::Ordering::Less;
        if q_bit {
            remainder.sub_assign(divisor);
        }
        // Collect quotient bits; only the last 128 matter (and by
        // construction the quotient fits exactly).
        hi = (hi << 1) | (lo >> 63);
        lo = (lo << 1) | u64::from(q_bit);
    }
    (hi, lo)
}

const SMALLEST: i32 = -342;
const LARGEST: i32 = 308;

fn main() {
    println!("//! 128-bit truncated powers of five for the Eisel-Lemire algorithm.");
    println!("//! Generated by `examples/gen_el_table.rs`; do not edit by hand.");
    println!();
    println!("/// `EL_POWERS[q + 342]` ≈ 5^q normalized to [2^127, 2^128), as (hi, lo).");
    println!(
        "pub(crate) const EL_POWERS: [(u64, u64); {}] = [",
        LARGEST - SMALLEST + 1
    );

    for q in SMALLEST..=LARGEST {
        let power5 = pow5(q.unsigned_abs());
        let b = power5.bit_length();
        let (hi, lo) = if q >= 0 {
            // 5^q normalized to exactly 128 bits: values that already fit
            // are shifted up (they fit u128, so plain integer math does it);
            // larger ones are truncated down to their top 128 bits.
            if b <= 128 {
                let lo_limb = power5.limbs.first().copied().unwrap_or(0);
                let hi_limb = power5.limbs.get(1).copied().unwrap_or(0);
                let value = (u128::from(hi_limb) << 64) | u128::from(lo_limb);
                let z = value << (128 - b);
                ((z >> 64) as u64, z as u64)
            } else {
                power5.top128()
            }
        } else {
            // Truncated reciprocal, rounded up (fast_float convention):
            // floor(2^(b + 127) / 5^|q|) + 1.
            let (hi, lo) = div_pow2(b + 127, &power5);
            let (lo2, carry) = lo.overflowing_add(1);
            (hi + u64::from(carry), lo2)
        };
        println!("    (0x{hi:016x}, 0x{lo:016x}), // q = {q}");
    }

    println!("];");
}
